from prometheus_client import Counter

llm_tokens_total = Counter(
    "llm_tokens_total",
    "Total tokens attributed to LLM calls (prompt + completion).",
    labelnames=("model",),
)

llm_tokens_prompt = Counter(
    "llm_tokens_prompt",
    "Prompt tokens processed by the LLM.",
    labelnames=("model",),
)

llm_tokens_completion = Counter(
    "llm_tokens_completion",
    "Completion tokens generated by the LLM.",
    labelnames=("model",),
)
